// <auto-generated />
using System;
using GraduateProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduateProject.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240526133511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraduateProject.Domain.Core.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("024d0c1c-d157-44cb-bece-708b10e3563d"),
                            Description = "Description of a book.",
                            Name = "Tom",
                            Price = 37
                        },
                        new
                        {
                            Id = new Guid("06adf48c-95c4-4a98-9049-827eb906b090"),
                            Description = "Description of a book.",
                            Name = "Bob",
                            Price = 41
                        },
                        new
                        {
                            Id = new Guid("3be3ce34-9f29-4189-8c87-7e6058361ccf"),
                            Description = "Description of a book.",
                            Name = "Sam",
                            Price = 24
                        });
                });

            modelBuilder.Entity("GraduateProject.Domain.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa1f8cb3-4f78-4cfc-a96e-d82ec3473bf7"),
                            Login = "qwe",
                            Password = "qwe"
                        },
                        new
                        {
                            Id = new Guid("196a36fe-07e9-4a79-9bca-d2eb02888b64"),
                            Login = "asd",
                            Password = "asd"
                        },
                        new
                        {
                            Id = new Guid("4e4135b5-0bb7-441f-be7c-3c6f1b80fc4c"),
                            Login = "dake",
                            Password = "dake"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
